name: polypeip
description: Application Polypeip.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  page_transition: ^1.1.5
  pull_to_refresh: ^1.5.7
  cached_network_image: ^2.2.0
  carousel_slider: ^2.0.0
  flutter_speed_dial: ^1.2.5
  url_launcher: ^5.4.5
  photo_view: ^0.9.2
  # flutter_datetime_picker: ^1.3.8
  image_picker: ^0.6.6+1
  statusbar: ^1.1.0
  mime: ^0.9.6+3
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_launcher_icons: ^0.7.5

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/img/start-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/logo_alt.png
    - assets/img/appbar-logo.png
    - assets/img/start-icon.png

  fonts:
    - family: Polypeip
      fonts:
        - asset: assets/fonts/Polypeip.ttf

    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
