/// Flutter icons Polypeip
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Polypeip
///      fonts:
///       - asset: fonts/Polypeip.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Polypeip {
  Polypeip._();

  static const _kFontFam = 'Polypeip';
  static const _kFontPkg = null;

  static const IconData checklist = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
